language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t samweeks/udemy-docker-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true samweeks/udemy-docker-docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "udemy-docker-docker-react"
    env: "UdemyDockerDockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-381364022671"
    bucket_path: "udemy-docker-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY